linters-settings:
  misspell:
    locale: US
  errcheck:
    ignore: github.com/bl4ko/netbox-ssot/internal/logger:.*

issues:
  max-issues-per-linter: 50
  max-same-issues: 20

linters:
  enable:
    # - gocyclo # TODO: enable in future
    # - gocognit # TODO: enable in future
    # - cyclop # TODO: enable in future
    # - errorlint # TODO: enable in future
    # - exhaustive # TODO: enable in future
    # - dupl # TODO: enable in future
    # - gochecknoglobals # TODO: enable in future
    - gocritic
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - execinquery
    - exportloopref
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - godot # TODO: enable in future
    # - goerr113 # TODO: enable in future
    - goheader
    - goimports
    # - gomnd # TODO: enable in future
    - gomoddirectives
    - goprintffuncname
    # - gosec # TODO: enable in future
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    # - ireturn # TODO: enable in future
    # - lll # TODO: enable in future
    # - maintidx # TODO: enable in future
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    # - nestif # TODO: enable in future
    - nilerr
    # - nilnil # TODO: enable in future
    - noctx
    - nolintlint
    - nosprintfhostport
    # - paralleltest # TODO: enable in future
    - prealloc
    - predeclared
    - promlinter
    - reassign
    # - revive # TODO: enable in future
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tenv
    - thelper
    - tparallel
    - unconvert
    # - unparam # TODO: enable in future
    - usestdlibvars
    - wastedassign
    # - whitespace # TODO: enable in future
    - zerologlint
