linters-settings:
  misspell:
    locale: US
  errcheck:
    exclude-functions:
      - (*github.com/bl4ko/netbox-ssot/internal/logger.Logger).Debug
      - (*github.com/bl4ko/netbox-ssot/internal/logger.Logger).Debugf
      - (*github.com/bl4ko/netbox-ssot/internal/logger.Logger).Info
      - (*github.com/bl4ko/netbox-ssot/internal/logger.Logger).Infof
      - (*github.com/bl4ko/netbox-ssot/internal/logger.Logger).Warning
      - (*github.com/bl4ko/netbox-ssot/internal/logger.Logger).Warningf
      - (*github.com/bl4ko/netbox-ssot/internal/logger.Logger).Error
      - (*github.com/bl4ko/netbox-ssot/internal/logger.Logger).Errorf
      - (*github.com/bl4ko/netbox-ssot/internal/logger.Logger).Output

issues:
  max-issues-per-linter: 50
  max-same-issues: 20
  exclude:
    - G402

linters:
  enable:
    - revive
    - gocyclo
    # - dupl # TODO: enable in future
    # - errorlint # TODO: enable in future
    # - gocognit # TODO: enable in future
    # - cyclop # TODO: enable in future
    # - paralleltest # TODO: enable in future
    # - lll # TODO: enable in future
    # - nestif # TODO: enable in future
    # - maintidx # TODO: enable in future
    # - exhaustive # TODO: enable in future
    # - nilnil # TODO: enable in future
    # - gochecknoglobals # TODO: enable in future
    # - goerr113 # TODO: enable in future
    # - ireturn # TODO: enable in future
    # - containedctx
    - gosec
    - gocritic
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - forcetypeassert
    - gci
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - godot
    - goheader
    - goimports
    - mnd
    - copyloopvar
    - gomoddirectives
    - goprintffuncname
    - gosmopolitan
    - grouper
    - importas
    - interfacebloat
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - zerologlint
