repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast linters runner for Go. Note that only modified files are linted, so linters like 'unused' that need to scan all files won't work as expected.
        entry: golangci-lint run --new-from-rev HEAD --fix
        types: [go]
        language: golang
        require_serial: true
        pass_filenames: false

      # - id: git-secrets
      #   name: Git Secrets
      #   description: git-secrets scans commits, commit messages, and --no-ff merges to prevent adding secrets into your git repositories.
      #   entry: "git-secrets --pre_commit_hook"
      #   language: script
