name: Bug Report
description: Report a bug or issue with netbox-ssot
title: "[Bug] <title>"
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! 🙏 Please take a few moments to fill out the details below.

        ⚠️ **Important Notes**:
        - Issues missing critical details may be closed without explanation.
        - Be sure to provide the requested **configuration**, **logs**, and other details. This helps us diagnose and resolve your issue faster.

  - type: dropdown
    id: urgent
    attributes:
      label: Is this urgent?
      description: Is this issue blocking critical functionality?
      options:
        - "No"
        - "Yes, it's critical"
        - "Yes, but it's not blocking"
    validations:
      required: true

  - type: dropdown
    id: method-of-running
    attributes:
      label: How are you running netbox-ssot?
      description: Select the method you are using to run netbox-ssot.
      options:
        - Docker
        - Podman
        - Kubernetes (K8s)
        - From source (Go)
        - Other
    validations:
      required: true

  - type: dropdown
    id: module-problem
    attributes:
      label: Which module has the issue?
      description: Indicate the module where the issue occurs.
      options:
        - General (not module-specific)
        - Parser
        - Inventory
        - Ovirt
        - VMware
        - DNAC
        - Proxmox
        - Palo Alto
        - Fortigate
        - FMC
        - IOS-XE
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: What version of netbox-ssot are you using?
      placeholder: "e.g., 1.5.0"
      description: Provide the exact version for better diagnostics.
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Share your configuration
      description: Provide your `configuration.yml` (excluding sensitive information) used with netbox-ssot.
      render: yaml
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What is the problem?
      placeholder: "Describe the issue you are experiencing."
      description: Include as much detail as possible about the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        Outline the exact steps needed to reproduce the issue, e.g.:
        1. Go to '...'
        2. Run '...'
        3. Observe the error.
      placeholder: "1. Step one...\n2. Step two...\n3. Error occurs..."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: "e.g., The feature should work as described in the documentation."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
      placeholder: "e.g., Instead of the expected behavior, the following error occurred..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Share DEBUG-level logs (remove sensitive information)
      description: Attach DEBUG-level logs for the session when the issue occurred. Make sure to redact sensitive data.
      render: plaintext

  - type: textarea
    id: environment
    attributes:
      label: Share your environment details
      description: Include additional information about your environment, such as OS, architecture, or dependencies.
      placeholder: "e.g., Ubuntu 22.04, x86_64, Docker 20.10.8"
