name: Deploy image to ghcr.io

on:
  push:
    tags:
      - v*
    # paths:
    #   - cmd/**
    #   - internal/**
    #   - pkg/**
    #   - Dockerfile
    #   - .dockerignore
    #   - .golangci.yml
    #   - go.mod
    #   - go.sum

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: bl4ko
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: bl4ko
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push final image
        uses: docker/build-push-action@v5.1.0
        with:
          platforms: linux/amd64,linux/arm64,linux/386,linux/arm/v6,linux/arm/v7
          tags: bl4ko/netbox-ssot:latest, bl4ko/netbox-ssot:$GITHUB_REF_NAME
          push: true
