name: Replace version in k8s manifests on main tag push
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  replace_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
          token: ${{ secrets.GH_TOKEN }}

      - name: Replace image version in k8s manifests
        run: |
          for file in k8s/*.yaml; do
             sed -i "s|ghcr.io/bl4ko/netbox-ssot:v.*.*.*|ghcr.io/bl4ko/netbox-ssot:${{ github.ref_name }}|g" "$file"
           done

      - name: Commit and push changes
        run: |
          git config --global user.name "svccicd"
          git config --global user.email "187764736+svccicd@users.noreply.github.com"
          git add .
          git commit -m "chore(k8s): Replace version in k8s manifests"
          git push -f origin main
